SELECT H.HACKER_ID
	 , H.NAME
	 , COUNT(C.HACKER_ID)
  FROM HACKERS H
	   INNER JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(C.HACKER_ID) = 
		(SELECT MAX(TEMP1.CNT)
		   FROM (SELECT COUNT(HACKER_ID) CNT
				   FROM CHALLENGES
				 GROUP BY HACKER_ID) TEMP1)
	OR COUNT(C.HACKER_ID) IN
		(SELECT T.CNT
		   FROM (SELECT COUNT(*) CNT
				   FROM CHALLENGES
				GROUP BY HACKER_ID) T
		GROUP BY T.CNT
		HAVING COUNT(T.CNT) = 1)

ORDER BY COUNT(C.HACKER_ID) DESC, H.HACKER_ID;