SELECT W.ID, P.AGE, W.COINS_NEEDED, W.[POWER]
  FROM WANDS W
INNER JOIN WANDS_PROPERTY P
    ON W.CODE = P.CODE
 WHERE IS_EVIL != 1 AND W.COINS_NEEDED = 
	   (
		SELECT MIN(WB.COINS_NEEDED)
		  FROM WANDS WB
		 INNER JOIN WANDS_PROPERTY PB
			ON WB.CODE = PB.CODE
		 WHERE PB.AGE = P.AGE 
		   AND WB.[POWER] = W.[POWER]
		)
ORDER BY W.[POWER] DESC, P.AGE DESC;