SELECT S.HACKER_ID, H.NAME
  FROM HACKERS H
 INNER JOIN SUBMISSIONS S
    ON H.HACKER_ID = S.HACKER_ID
 INNER JOIN CHALLENGES C
    ON C.CHALLENGE_ID = S.CHALLENGE_ID
 INNER JOIN DIFFICULTY D
    ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
 WHERE S.SCORE = D.SCORE 
   AND C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
GROUP BY S.HACKER_ID, H.NAME
HAVING COUNT(S.HACKER_ID) > 1
ORDER BY COUNT(S.HACKER_ID) DESC, S.HACKER_ID ASC;