SELECT MIN(DOCTOR)
	 , MIN(PROFESSOR)
	 , MIN(SINGER)
	 , MIN(ACTOR)
FROM
	(SELECT CASE WHEN OCCUPATION = "DOCTOR" THEN NAME END AS DOCTOR
		  , CASE WHEN OCCUPATION = "PROFESSOR" THEN NAME END AS PROFESSOR
		  ,	CASE WHEN OCCUPATION = "SINGER" THEN NAME END AS SINGER
		  , CASE WHEN OCCUPATION = "ACTOR" THEN NAME END AS ACTOR
		  , RANK() OVER(PARTITION BY OCCUPATION	ORDER BY NAME) AS OCCU_RANK
		  FROM OCCUPATIONS) X
	GROUP BY OCCU_RANK;