SELECT CONCAT(NAME,
		CASE WHEN OCCUPATION = "PROFESSOR"
			 THEN "(P)"
			 WHEN OCCUPATION = "DOCTOR"
			 THEN "(D)"
			 WHEN OCCUPATION = "ACTOR"
			 THEN "(A)"
			 WHEN OCCUPATION = "SINGER"
			 THEN "(S)"
			 END)
  FROM OCCUPATIONS
ORDER BY NAME;

SELECT "There are a total of ", COUNT(OCCUPATION), CONCAT(LOWER(OCCUPATION), "s.")
  FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION) ASC, OCCUPATION ASC;