/*
Query in MSSQL
*/
SELECT TOP 1 CITY, LEN(CITY)
  FROM STATION
ORDER BY LEN(CITY);

SELECT TOP 1 CITY, LEN(CITY)
  FROM STATION
ORDER BY LEN(CITY) DESC

/*
Query in MySQL. VS errors out query.
*/
/*
SELECT CITY, LENGTH(CITY)
  FROM STATION
ORDER BY LENGTH(CITY), CITY LIMIT 1;

SELECT CITY, LENGTH(CITY)
  FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1;
*/